config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :recyclers

 root 'static#home'
 get '/sign-in' => 'sessions#new'
 delete '/sign-out' => 'sessions#destroy'
 get  '/about' => 'static#about'
 get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: :cat_pictures

end

app/models/recycler.rb
class Recycler < ActiveRecord::Base
	validates_presence_of :name, :address
	validates_format_of :phone, with: /\A\d{3}-\d{3}-\d{4}\z/, message: "isn't a correctly formatted phone number: e.g. 123-456-7890", allow_blank: true
	before_validation :format_website
	validate :valid_website

	def format_website
	  self.website = "http://#{website}" unless website.blank? || website[/^https?/]
	end

	def valid_website
	  return if website.blank?
	  if /(\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z)/ix =~ website
	    begin # check header response
	      response = Net::HTTP.get_response URI.parse(website)
	      return if response.kind_of?(Net::HTTPSuccess) || response.kind_of?(Net::HTTPRedirection)
	      message = "doesn't appear to be a page on #{response.uri.host} (#{response.code}: #{response.msg})"
	    rescue # Recover on DNS failures
	      message = "doesn't seem to exist on the web"
	    end
	  end
	  message ||= "isn't a valid web address"
	  errors.add(:website, message)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

	def current_user
		User.find_by(id: session[:user_id])
	end
	helper_method :current_user

	def user_signed_in?
		!!current_user
	end
	helper_method :user_signed_in?

	def only_allow_signed_in_users
	  unless user_signed_in?
	    redirect_to sign_in_url, notice: 'You must sign in to access this part of the app.'
	  end
	end
	helper_method :only_allow_signed_in_users
	
end

app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  before_action :set_recycler, only: [:show, :edit, :update, :destroy]
  before_action :only_allow_signed_in_users, except: [:index, :show]

  # GET /recyclers
  # GET /recyclers.json
  def index
    @recyclers = Recycler.all
  end

  # GET /recyclers/1
  # GET /recyclers/1.json
  def show
  end

  # GET /recyclers/new
  def new
    @recycler = Recycler.new
  end

  # GET /recyclers/1/edit
  def edit
  end

  # POST /recyclers
  # POST /recyclers.json
  def create
    @recycler = Recycler.new(recycler_params)

    respond_to do |format|
      if @recycler.save
        format.html { redirect_to @recycler, notice: 'Recycler was successfully created.' }
        format.json { render :show, status: :created, location: @recycler }
      else
        format.html { render :new }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recyclers/1
  # PATCH/PUT /recyclers/1.json
  def update
    respond_to do |format|
      if @recycler.update(recycler_params)
        format.html { redirect_to @recycler, notice: 'Recycler was successfully updated.' }
        format.json { render :show, status: :ok, location: @recycler }
      else
        format.html { render :edit }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recyclers/1
  # DELETE /recyclers/1.json
  def destroy
    @recycler.destroy
    respond_to do |format|
      format.html { redirect_to recyclers_url, notice: 'Recycler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recycler
      @recycler = Recycler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recycler_params
      params.require(:recycler).permit(:name, :address, :phone, :website, :email, :accepts_white_computer_paper, :accepts_corrugated_cardboard, :accepts_color_seperated_glass)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged In!"
  	else
  		flash.alert = 'Invalid email/password combination. Please try again'
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: 'Successfully signed out!'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
  	@cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recyclers_helper.rb
module RecyclersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
	def current_date_and_time
    curTime = Time.now
    return curTime.strftime("%-B %-e, %-Y at %-l:%M%P")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h2>Menu:</h2>
<ul>
	<li><%= link_to 'Home', root_path %></li>
	<li><%= link_to 'About',about_path %></li>
	<li><%= link_to 'Cat Pics', cat_pictures_path %></li>
</ul>
<%= yield %>

</body>
</html>

app/views/recyclers/_form.html.erb
<%= form_for(@recycler) do |f| %>
  <% if @recycler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recycler.errors.count, "error") %> prohibited this recycler from being saved:</h2>

      <ul>
      <% @recycler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_area :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :accepts_white_computer_paper %><br>
    <%= f.check_box :accepts_white_computer_paper %>
  </div>
  <div class="field">
    <%= f.label :accepts_corrugated_cardboard %><br>
    <%= f.check_box :accepts_corrugated_cardboard %>
  </div>
  <div class="field">
    <%= f.label :accepts_color_seperated_glass %><br>
    <%= f.check_box :accepts_color_seperated_glass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recyclers/edit.html.erb
<h1>Editing recycler</h1>

<%= render 'form' %>

<%= link_to 'Show', @recycler %> |
<%= link_to 'Back', recyclers_path %>

app/views/recyclers/index.html.erb
<h1>Listing recyclers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Email</th>
      <th>Accepts white computer paper</th>
      <th>Accepts corrugated cardboard</th>
      <th>Accepts color seperated glass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recyclers.each do |recycler| %>
      <tr>
        <td><%= recycler.name %></td>
        <td><%= recycler.address %></td>
        <td><%= recycler.phone %></td>
        <td><%= recycler.website %></td>
        <td><%= recycler.email %></td>
        <td><%= recycler.accepts_white_computer_paper %></td>
        <td><%= recycler.accepts_corrugated_cardboard %></td>
        <td><%= recycler.accepts_color_seperated_glass %></td>
        <td><%= link_to 'Show', recycler %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_recycler_path(recycler) %></td>
        <td><%= link_to 'Destroy', recycler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recycler', new_recycler_path %>

app/views/recyclers/new.html.erb
<h1>New recycler</h1>

<%= render 'form' %>

<%= link_to 'Back', recyclers_path %>

app/views/recyclers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recycler.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @recycler.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @recycler.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @recycler.website %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recycler.email %>
</p>

<p>
  <strong>Accepts white computer paper:</strong>
  <%= @recycler.accepts_white_computer_paper %>
</p>

<p>
  <strong>Accepts corrugated cardboard:</strong>
  <%= @recycler.accepts_corrugated_cardboard %>
</p>

<p>
  <strong>Accepts color seperated glass:</strong>
  <%= @recycler.accepts_color_seperated_glass %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_recycler_path(@recycler) %> |
<%= link_to 'Back', recyclers_path %>
<% else %>
<%= link_to 'Back', recyclers_path %>
<% end %>